spring.datasource.url=jdbc:mysql://mysql-1bbd440b-saatvika0507-8ed7.b.aivencloud.com:24066/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_oqyAn7pE-fDETAJ4Qn7
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8080
spring.web.cors.allowed-origins=*
